### ISSUE TITLE
Implement grocery store homepage

### ISSUE THREAD

**Issue by peixuan917** [SEPP-SSH-4-0/SEPP#31]
Create index.hmtl (grocery store homepage) 

Implement functions to fetch grocery products data from Firebase's database to display in index.html

Add styling the page as required

**Comment by Maximus9986** [comment]
Added grocery store homepage that fetches data from Firebase db to display to users

Implemented functions - displayProducts(), addToSharedCart(), incrementCartCount(), updateCartCount()
