### ISSUE TITLE
Implement Cart Feature

### ISSUE THREAD

**Issue by shiwoyaaa** [SEPP-SSH-4-0/SEPP#32]
Create a cart.html page which displays items and user can added item to the cart.

Implement JavaScript logic to add items to the cart.

Implement remove items and update the quantity function.

**Comment by peixuan917** [comment]
Implemented logic to fetch cart data for each user, displaying each user's breakdowns in the cart-summary container

Implemented logic to split delivery and service fees among participating members

Added styling
